-- Migration: Initial Treefolio schema
-- Created: 2026-02-17
-- Description: Creates all tf_-prefixed tables, indexes, and triggers for the Treefolio app.
--
-- Rollback:
--   DROP TRIGGER IF EXISTS tf_trees_updated_at ON tf_trees;
--   DROP FUNCTION IF EXISTS tf_update_updated_at();
--   DROP TABLE IF EXISTS tf_chat_messages;
--   DROP TABLE IF EXISTS tf_care_recommendations;
--   DROP TABLE IF EXISTS tf_journal_entries;
--   DROP TABLE IF EXISTS tf_tree_images;
--   DROP TABLE IF EXISTS tf_trees;
--   DROP TABLE IF EXISTS tf_species;

-- ============================================================
-- Species reference table
-- ============================================================
CREATE TABLE tf_species (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scientific_name TEXT UNIQUE NOT NULL,
  common_name TEXT NOT NULL,
  family TEXT,
  care_calendar JSONB NOT NULL DEFAULT '{}',
  climate_zones INTEGER[] DEFAULT '{}',
  indoor_outdoor TEXT CHECK (indoor_outdoor IN ('indoor', 'outdoor', 'both')),
  difficulty TEXT CHECK (difficulty IN ('beginner', 'intermediate', 'advanced')),
  watering TEXT,
  light TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- User's tree collection
-- ============================================================
CREATE TABLE tf_trees (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  species_id UUID REFERENCES tf_species(id),
  age_years INTEGER,
  acquired_date DATE,
  source TEXT,
  style TEXT,
  size_class TEXT CHECK (size_class IN ('mame', 'shohin', 'kifu', 'chuhin', 'dai')),
  pot_type TEXT,
  soil_mix TEXT,
  description TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- Tree images
-- ============================================================
CREATE TABLE tf_tree_images (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tree_id UUID REFERENCES tf_trees(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  caption TEXT,
  angle TEXT CHECK (angle IN ('front', 'back', 'left', 'right', 'top', 'detail', 'roots', 'canopy', 'full')),
  taken_at DATE,
  uploaded_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- Journal / timeline entries
-- ============================================================
CREATE TABLE tf_journal_entries (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tree_id UUID REFERENCES tf_trees(id) ON DELETE CASCADE,
  entry_type TEXT NOT NULL CHECK (entry_type IN ('prune', 'repot', 'water', 'fertilize', 'wire', 'defoliate', 'style', 'photo', 'health', 'note')),
  content TEXT,
  images TEXT[] DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- Weekly care recommendations (generated by LLM + weather)
-- ============================================================
CREATE TABLE tf_care_recommendations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tree_id UUID REFERENCES tf_trees(id) ON DELETE CASCADE,
  week_start DATE NOT NULL,
  recommendations JSONB NOT NULL,
  weather_snapshot JSONB,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(tree_id, week_start)
);

-- ============================================================
-- Chat history
-- ============================================================
CREATE TABLE tf_chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  session_id UUID NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
  content TEXT NOT NULL,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- Indexes
-- ============================================================
CREATE INDEX idx_tf_trees_species ON tf_trees(species_id);
CREATE INDEX idx_tf_tree_images_tree ON tf_tree_images(tree_id);
CREATE INDEX idx_tf_journal_tree ON tf_journal_entries(tree_id);
CREATE INDEX idx_tf_journal_type ON tf_journal_entries(entry_type);
CREATE INDEX idx_tf_care_rec_tree_week ON tf_care_recommendations(tree_id, week_start);
CREATE INDEX idx_tf_chat_session ON tf_chat_messages(session_id);

-- ============================================================
-- updated_at trigger function
-- ============================================================
CREATE OR REPLACE FUNCTION tf_update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER tf_trees_updated_at
  BEFORE UPDATE ON tf_trees
  FOR EACH ROW EXECUTE FUNCTION tf_update_updated_at();
